<?xml version="1.0" encoding="UTF-8"?>
<testsuites name="Mocha Tests" time="14.010" tests="4" failures="1">
  <testsuite name="Root Suite" timestamp="2024-06-17T12:40:50" tests="0" file="cypress\e2e\webtable.cy.js" time="0.000" failures="0">
  </testsuite>
  <testsuite name="Handle Tables" timestamp="2024-06-17T12:40:50" tests="4" time="14.005" failures="1">
    <testcase name="Handle Tables Check Number Rows &amp; Columns" time="3.675" classname="Check Number Rows &amp; Columns">
    </testcase>
    <testcase name="Handle Tables Check cell data from specific row &amp; Column" time="2.590" classname="Check cell data from specific row &amp; Column">
    </testcase>
    <testcase name="Handle Tables &quot;before each&quot; hook: Login for &quot;Read all the rows &amp; Columns data in the first page&quot;" time="0.000" classname="&quot;before each&quot; hook: Login for &quot;Read all the rows &amp; Columns data in the first page&quot;">
      <failure message="Timed out retrying after 4000ms: Expected to find element: `//a[text()=&apos; Customers&apos;]`, but never found it.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`" type="AssertionError"><![CDATA[AssertionError: Timed out retrying after 4000ms: Expected to find element: `//a[text()=' Customers']`, but never found it.

Because this error occurred during a `before each` hook we are skipping the remaining tests in the current suite: `Handle Tables`
    at Context.eval (webpack://cypressautomation/./cypress/e2e/webtable.cy.js:13:11)]]></failure>
    </testcase>
  </testsuite>
</testsuites>